<?php
/**
 * Copyright(c) 2016, 9WPThemes
 * @filename: default-content.php
 * @time    : 10/17/16 5:36 PM
 * @author  : 9WPThemes Team
 */

if ( !defined( 'ABSPATH' ) ) {
    die( '-1' );
}

//$template_group = __( 'Default Content | ', 'w9-floral-addon' );
//$predefined_templates_list[] = array(
//    'name'    => $template_group . __( 'Portfolio Single', 'w9-floral-addon' ),
//    'content' => '[vc_row][vc_column text_color="__" heading_color="__" link_color="__" link_hover_color="__" offset="vc_col-lg-9 vc_col-md-8" css=".vc_custom_1481674331639{padding-bottom: 55px !important;}"][floral_shortcode_thumbnail_slider s1_image_ratio="0.5"][/vc_column][vc_column text_color="__" heading_color="__" link_color="__" link_hover_color="__" offset="vc_col-lg-3 vc_col-md-4" css=".vc_custom_1481674366327{padding-bottom: 30px !important;}"][floral_shortcode_heading heading_title="PROJECT INFO" heading_title_size="custom" heading_title_custom_size="14" heading_title_line_height="1" heading_subtitle_enable="0" heading_separator_enable="1" heading_separator_width="custom-width" heading_separator_custom_width="40px" heading_title_responsive_title_size="0"][vc_column_text css=".vc_custom_1481674302737{margin-bottom: 15px !important;}"]Floral Inc traces its roots back to 1989 in Colorado and since then have never looked back.[/vc_column_text][floral_shortcode_portfolio_info info_list="%5B%7B%22info%22%3A%22client%22%2C%22info_label%22%3A%22CLIENT%22%7D%2C%7B%22info%22%3A%22categories%22%2C%22info_label%22%3A%22CATEGORIES%22%7D%2C%7B%22info%22%3A%22date%22%2C%22info_label%22%3A%22DATE%22%7D%2C%7B%22info%22%3A%22addition-info%22%7D%5D"][/vc_column][vc_column][vc_empty_space height="1px" css=".vc_custom_1481670465499{background-color: #eeeeee !important;}"][/vc_column][/vc_row][vc_row equal_height="yes" text_color="__" heading_color="__" link_color="__" link_hover_color="__" css=".vc_custom_1481674845942{padding-top: 50px !important;padding-bottom: 25px !important;}"][vc_column text_color="__" heading_color="__" link_color="__" link_hover_color="__" width="2/3" tablet_css=".vc_custom_1481674680975{padding-left: 15px !important;}" mobile_css=".vc_custom_1481674680976{padding-right: 15px !important;}" css=".vc_custom_1481674680975{padding-bottom: 25px !important;}"][floral_shortcode_portfolio_about][/vc_column][vc_column text_color="__" heading_color="__" link_color="__" link_hover_color="__" width="1/3" tablet_css=".vc_custom_1481671288354{padding-left: 15px !important;}" mobile_css=".vc_custom_1481671288355{padding-left: 15px !important;}"][floral_shortcode_heading heading_title="PROJECT BROCHURE" heading_title_size="custom" heading_title_custom_size="14" heading_title_line_height="1" heading_subtitle_enable="0" heading_separator_enable="1" heading_separator_width="custom-width" heading_separator_custom_width="40px" heading_title_responsive_title_size="0" css=".vc_custom_1481674867858{margin-bottom: 35px !important;}"][floral_shortcode_widget_download floral_remove_default_mb="1"][floral_shortcode_widget_download floral_remove_default_mb="1"][floral_shortcode_widget_download floral_remove_default_mb="0"][/vc_column][/vc_row]'
//);
//$predefined_templates_list[] = array(
//    'name'    => $template_group . __( 'Service Single', 'w9-floral-addon' ),
//    'content' => '[vc_row][vc_column][floral_shortcode_heading heading_title_data_source="raw-page-title" heading_title_size="custom" heading_title_custom_size="14" heading_title_line_height="1" heading_title_text_transform="text-uppercase" heading_subtitle_enable="0" heading_separator_enable="1" heading_separator_width="custom-width" heading_separator_custom_width="40px" heading_title_responsive_title_size="0" css=".vc_custom_1481727452045{margin-bottom: 35px !important;}"][floral_shortcode_thumbnail_slider][vc_empty_space height="50px" css=".vc_custom_1481732716401{border-bottom-width: 1px !important;border-bottom-color: #eeeeee !important;border-bottom-style: solid !important;}"][/vc_column][/vc_row]'
//);
//$predefined_templates_list[] = array(
//    'name'    => $template_group . __( 'Portfolio Single Style 02', 'w9-floral-addon' ),
//    'content' => '[vc_row overlay_set="show_overlay_color" overlay_color="rgba(0,0,0,0.5)" text_color="light" heading_color="light" link_color="light" link_hover_color="__" el_class="floral-portfolio-title-row" css=".vc_custom_1472661162831{padding-top: 200px !important;padding-bottom: 200px !important;}" tablet_css=".vc_custom_1472661162832{padding-top: 120px !important;padding-bottom: 120px !important;}" mobile_css=".vc_custom_1472661162833{padding-top: 80px !important;padding-bottom: 80px !important;}"][vc_column][floral_shortcode_portfolio_page_title add_button="yes" btn_shape="btn-shape-rounded-2" btn_icon_align="align-icon-right" type="9wpthemes" icon_9wpthemes="w9 w9-ico-ios-arrow-thin-right" btn_icon_effect="icon-effect-inner-out-text" btn_text_hover_color="__" btn_bgc_hover_color="bolder" btn_add_icon="1"][/vc_column][/vc_row][vc_row text_color="__" heading_color="__" link_color="__" link_hover_color="__" css=".vc_custom_1474691097251{padding-top: 120px !important;padding-bottom: 60px !important;}" tablet_css=".vc_custom_1474691097252{padding-top: 80px !important;padding-bottom: 20px !important;}" mobile_css=".vc_custom_1474691097253{padding-top: 60px !important;padding-bottom: 0px !important;}"][vc_column text_color="__" heading_color="__" link_color="__" link_hover_color="__" width="2/3" offset="vc_col-lg-9"][floral_shortcode_portfolio_gallery gallery_type="simple" img_size="floral_870"][/vc_column][vc_column text_color="__" heading_color="__" link_color="__" link_hover_color="__" width="1/3" offset="vc_col-lg-3"][floral_shortcode_portfolio_about][floral_shortcode_portfolio_info add_button="yes" btn_shape="btn-shape-rounded-2" btn_icon_align="align-icon-right" type="9wpthemes" icon_9wpthemes="w9 w9-ico-ios-arrow-thin-right" btn_icon_effect="icon-effect-inner-out-text" btn_text_hover_color="__" btn_bgc_hover_color="bolder" btn_add_icon="1"][/vc_column][/vc_row]'
//);
