<?php
/**
 * Copyright(c) 2016, 9WPThemes
 * @filename: floral-button.php
 * @time    : 9/7/16 6:05 PM
 * @author  : 9WPThemes Team
 */

if ( !defined( 'ABSPATH' ) ) {
    die( '-1' );
}

$presets_settings['floral_shortcode_button'] = array(
    array(
        'name'     => __( 'Floral Common', 'w9-floral-addon' ),
//        'default'  => true,
        'settings' => array (
            'btn_text' => 'The button text',
            'btn_link' => '',
            'btn_ff' => 's-font',
            'btn_style' => 'btn-style-solid',
            'btn_shape' => 'btn-shape-rounded-2',
            'btn_size' => 'btn-size-md',
            'btn_custom_size' => '',
            'btn_custom_padding_lr' => '',
            'btn_custom_width' => '',
            'btn_alignment' => 'inline-block-el',
            'btn_add_icon' => '1',
            'btn_icon_align' => 'align-icon-right',
            'type' => '9wpthemes',
            'icon_9wpthemes' => 'w9 w9-ico-ios-arrow-thin-right',
            'btn_icon_effect' => 'icon-effect-none',
            'btn_icon_size' => '175%',
            'btn_text_color' => 'light',
            'btn_text_custom_color' => '',
            'btn_bgc' => 'p',
            'btn_bgc_gradient_1' => 'p',
            'btn_bgc_gradient_2' => 's',
            'btn_bgc_gradient_angle' => '45',
            'btn_bgc_custom_color' => '',
            'btn_border_color' => 'transparent',
            'btn_border_custom_color' => '',
            'btn_text_hover_color' => '__',
            'btn_text_hover_custom_color' => '',
            'btn_bgc_hover_color' => 'bolder',
            'btn_bgc_hover_custom_color' => '',
            'btn_border_hover_color' => 'none',
            'btn_border_hover_custom_color' => '',
            'btn_box_shadow_color' => 'bolder',
            'btn_box_shadow_custom_color' => '',
            'btn_hover_effect' => 'hover-effect-default',
            'btn_down_effect' => '',
            'btn_opacity_effect' => '1',
            'btn_custom_onclick' => 'none',
        ),
    ),
    array(
        'name'     => __( 'Floral Gradient', 'w9-floral-addon' ),
        'default'  => false,
        'settings' => array (
            'btn_text' => 'Button',
            'btn_link' => '',
            'btn_ff' => 's-font',
            'btn_style' => 'btn-style-solid',
            'btn_shape' => 'btn-shape-square',
            'btn_size' => 'btn-size-md',
            'btn_custom_size' => '',
            'btn_custom_padding_lr' => '',
            'btn_custom_width' => '',
            'btn_alignment' => 'inline-block-el',
            'btn_add_icon' => '0',
            'btn_icon_align' => 'align-icon-left',
            'type' => '',
            'icon_9wpthemes' => '',
            'icon_fontawesome' => '',
            'icon_openiconic' => '',
            'icon_typicons' => '',
            'icon_entypo' => '',
            'icon_linecons' => '',
            'icon_monosocial' => '',
            'btn_icon_effect' => 'icon-effect-none',
            'btn_icon_size' => '100%',
            'btn_text_color' => 'light',
            'btn_text_custom_color' => '',
            'btn_bgc' => 'gradient',
            'btn_bgc_gradient_1' => 'p',
            'btn_bgc_gradient_2' => 's',
            'btn_bgc_gradient_angle' => '45',
            'btn_bgc_custom_color' => '',
            'btn_border_color' => 'transparent',
            'btn_border_custom_color' => '',
            'btn_text_hover_color' => '__',
            'btn_text_hover_custom_color' => '',
            'btn_bgc_hover_color' => 'meta-text',
            'btn_bgc_hover_custom_color' => '',
            'btn_border_hover_color' => 'none',
            'btn_border_hover_custom_color' => '',
            'btn_box_shadow_color' => 'bolder',
            'btn_box_shadow_custom_color' => '',
            'btn_hover_effect' => 'hover-effect-default',
            'btn_down_effect' => '',
            'btn_opacity_effect' => '1',
            'btn_custom_onclick' => 'none',
            'btn_content_template_popup' => 'page-title-archive-portfolio',
            'btn_sidebar_popup' => 'sidebar-1',
            'btn_custom_onclick_code' => '',
            'el_class' => '',
            'css' => '',
            'animation_css' => '',
            'animation_duration' => '',
            'animation_delay' => '',
        ),
    ),
    array(
        'name'     => __( 'Basic Square', 'w9-floral-addon' ),
        'default'  => false,
        'settings' => array (
            'btn_text' => 'Button',
            'btn_link' => '',
            'btn_ff' => 's-font',
            'btn_style' => 'btn-style-solid',
            'btn_shape' => 'btn-shape-square',
            'btn_size' => 'btn-size-md',
            'btn_custom_size' => '',
            'btn_custom_padding_lr' => '',
            'btn_custom_width' => '',
            'btn_alignment' => 'inline-block-el',
            'btn_add_icon' => '0',
            'btn_icon_align' => 'align-icon-left',
            'type' => '',
            'icon_9wpthemes' => '',
            'icon_fontawesome' => '',
            'icon_openiconic' => '',
            'icon_typicons' => '',
            'icon_entypo' => '',
            'icon_linecons' => '',
            'icon_monosocial' => '',
            'btn_icon_effect' => 'icon-effect-none',
            'btn_icon_size' => '100%',
            'btn_text_color' => 'light',
            'btn_text_custom_color' => '',
            'btn_bgc' => 'p',
            'btn_bgc_gradient_1' => 'p',
            'btn_bgc_gradient_2' => 's',
            'btn_bgc_gradient_angle' => '45',
            'btn_bgc_custom_color' => '',
            'btn_border_color' => 'transparent',
            'btn_border_custom_color' => '',
            'btn_text_hover_color' => '__',
            'btn_text_hover_custom_color' => '',
            'btn_bgc_hover_color' => 'bolder',
            'btn_bgc_hover_custom_color' => '',
            'btn_border_hover_color' => 'none',
            'btn_border_hover_custom_color' => '',
            'btn_box_shadow_color' => 'bolder',
            'btn_box_shadow_custom_color' => '',
            'btn_hover_effect' => 'hover-effect-default',
            'btn_down_effect' => '',
            'btn_opacity_effect' => '1',
            'btn_custom_onclick' => 'none',
            'btn_content_template_popup' => 'page-title-archive-portfolio',
            'btn_sidebar_popup' => 'sidebar-1',
            'btn_custom_onclick_code' => '',
            'el_class' => '',
            'css' => '',
            'animation_css' => '',
            'animation_duration' => '',
            'animation_delay' => '',
        )
    ),
    array(
        'name'     => __( 'Basic Circle', 'w9-floral-addon' ),
        'default'  => false,
        'settings' => array (
            'btn_text' => 'Button',
            'btn_link' => '',
            'btn_ff' => 's-font',
            'btn_style' => 'btn-style-solid',
            'btn_shape' => 'btn-shape-rounded-2',
            'btn_size' => 'btn-size-md',
            'btn_custom_size' => '',
            'btn_custom_padding_lr' => '',
            'btn_custom_width' => '',
            'btn_alignment' => 'inline-block-el',
            'btn_add_icon' => '0',
            'btn_icon_align' => 'align-icon-left',
            'type' => '',
            'icon_9wpthemes' => '',
            'icon_fontawesome' => '',
            'icon_openiconic' => '',
            'icon_typicons' => '',
            'icon_entypo' => '',
            'icon_linecons' => '',
            'icon_monosocial' => '',
            'btn_icon_effect' => 'icon-effect-none',
            'btn_icon_size' => '100%',
            'btn_text_color' => 'light',
            'btn_text_custom_color' => '',
            'btn_bgc' => 'p',
            'btn_bgc_gradient_1' => 'p',
            'btn_bgc_gradient_2' => 's',
            'btn_bgc_gradient_angle' => '45',
            'btn_bgc_custom_color' => '',
            'btn_border_color' => 'transparent',
            'btn_border_custom_color' => '',
            'btn_text_hover_color' => '__',
            'btn_text_hover_custom_color' => '',
            'btn_bgc_hover_color' => 'bolder',
            'btn_bgc_hover_custom_color' => '',
            'btn_border_hover_color' => 'none',
            'btn_border_hover_custom_color' => '',
            'btn_box_shadow_color' => 'bolder',
            'btn_box_shadow_custom_color' => '',
            'btn_hover_effect' => 'hover-effect-default',
            'btn_down_effect' => '',
            'btn_opacity_effect' => '1',
            'btn_custom_onclick' => 'none',
            'btn_content_template_popup' => 'page-title-archive-portfolio',
            'btn_sidebar_popup' => 'sidebar-1',
            'btn_custom_onclick_code' => '',
            'el_class' => '',
            'css' => '',
            'animation_css' => '',
            'animation_duration' => '',
            'animation_delay' => '',
        )
    ),
    
);
        